%YAML 1.2
---

# The class to initialise, and init parameters
class:
  mxcubecore.HardwareObjects.Beamline.Beamline

objects:
  !!omap
  - session: session.yaml
  - machine_info: machine_info.yaml
  - detector: detector.yaml
  - beam: beam.yaml
  - bluesky: bluesky.yaml
  - sample_changer: sample_changer.yaml
  - cryo: cryo.yaml
  - wavelength: wavelength.yaml
  - energy: energy.yaml
  - phase: phase.yaml
  - detector_distance: detector_distance.yaml
  - resolution: resolution.yaml
  - diffractometer: diffractometer.yaml
  - lims: lims.yaml
  - sample_view: sample_view.yaml
  - queue_manager: queue_manager.yaml
  - queue_model: queue_model.yaml
  - transmission: transmission.yaml
  - flux: flux.yaml
  - beamline_actions: beamline_actions.yaml
  - collect: mxcollect.yaml
  - safety_shutter: safety_shutter.yaml

configuration:
  advanced_methods:
    - MeshScan
    - XrayCentering

  tunable_wavelength: true
  disable_num_passes: true
  run_processing_parallel: true
  run_number: 1
  click_centring_num_clicks: 3

  mesh_result_format: PNG
  use_native_mesh: true
  enable_2d_points: true

  default_acquisition_parameters:
    default:
      exp_time: 0.01
      osc_start: 0.0
      osc_range: 0.1
      num_passes: 1
      first_image: 1
      overlap: 0
      num_images: 1
      detector_mode: 1
      inverse_beam: false
      take_dark_current: true
      skip_existing_images: true
      take_snapshots: true
      sub_wedge_size: 10

      helical:
        number_of_images: 100
        detector_mode_list: ["0", "C18", "C2"]

    characterisation:
      exp_time: 0.05
      osc_range: 1
      overlap: -89
      num_images: 4
      shutterless: false
      detector_mode_list: ["0", "C18", "C2"]

    mesh:
      exp_time: 10
      range: 10
      num_images: 100
      cell_counting: zig-zag
      cell_spacing: vertical, horizontal
      mesh_center: top-left

      gphlworkflow:
        {}

  acquisition_limit_values:
    exposure_time:
      - 0.00025
      - 1
    osc_range:
      - 0.05
      - 10
    number_of_images:
      - 1
      - 9999
    kappa:
      - -95
      - 1

  available_methods:
    datacollection: true
    characterisation: false
    helical: false
    xrf_spectrum: true
    energy_scan: false
    mesh: true
    ssx_chip_collection: false
    gphlworkflow: false
    test_collection: false
